
openapi: 3.0.1
info:
  title: User Service - v3
  termsOfService: https://example.com/terms/
  contact:
    name: API Support Team
    url: https://www.test.com/support
    email: support@test.com
  license:
    name: Apache 8.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.2
paths:
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        required: false
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                required:
                  - id
                type: object
security:
  - customer_auth:
    - write:customer
    - read:users
servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
- url: https://gigantic-server.com/v1
  description: Production server
- url: https://gigantic-server-uat.com/v1
  description: UAT server
tags:
  - name: pet
    description: Pets operations
  - name: petFlow
    description: Pets
externalDocs:
  description: Find more info here
  url: https://test.com
