
openapi: 3.0.2
info:
  title: User Service
  termsOfService: https://example.com/terms/
  contact:
    name: API Support-v1
    url: https://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.5
paths:
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                required:
                  - id
                type: object
security:
  - customer_auth:
    - write:customer
    - read:users
  - petstore_authh:
    - write:pets
    - read:pets
servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
- url: https://api.gigantic-server.com/v1
  description: Production UAT
tags:
  - name: pet
    description: Pets operations
  - name: petFlow
    description: Pets
externalDocs:
  description: Find more info here
  url: https://exle.com
