
openapi: 3.0.2
info:
  title: User Service
  version: 1.0.0
  termsOfService: https://example.com/terms/
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
paths:
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                required:
                  - id
                type: object
security:
  - customer_auth:
    - write:customer
    - read:users
  - petstore_auth:
    - write:pets
    - read:pets
servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
- url: https://api.gigantic-server.com/v1
  description: Production UAT
tags:
  - name: pet
    description: Pets operations
  - name: customer
    description: customer
externalDocs:
  description: Find more info here
  url: https://example.com
